apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: my-ai-test1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  my-ai-test1
    app.kubernetes.io/part-of: my-ai-test1-gitops  
  name: my-ai-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  my-ai-test1 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  my-ai-test1
    spec:
      containers:
      - image: quay.io/redhat-appstudio/dance-bootstrap-app:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080 
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080 
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080 
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi    
        envFrom:
        - configMapRef:
            name: my-ai-test1-model-config
        env:
        - name: GIT_REPO
          value: https://github.com/sjm-rhtap/my-ai-test1-gitops
        - name: MODEL_ENDPOINT_BEARER
          valueFrom:
            secretKeyRef:
              name: model-bearer-secret
              key: API_KEY
      imagePullSecrets:
        - name: tssc-image-registry-auth
