apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: my-ai-test1
  janus-idp.io/tekton: my-ai-test1
  backstage.io/kubernetes-id: my-ai-test1
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: my-ai-test1
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
