apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: my-ai-test1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-ai-test1 
  name: my-ai-test1
spec:
  port:
    targetPort: 8080 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: my-ai-test1
    weight: 100 
